# Generated by Django 4.0.2 on 2022-02-07 12:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='market',
            options={'ordering': ('-id',), 'verbose_name': '마켓', 'verbose_name_plural': '마켓들'},
        ),
    ]
