# Generated by Django 4.0.2 on 2022-02-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DbVar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='등록날짜')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='갱신날짜')),
                ('expire_date', models.DateTimeField(null=True, verbose_name='만료날짜')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='변수이름')),
                ('value', models.TextField(verbose_name='변수값')),
            ],
        ),
    ]
