# Generated by Django 4.0.2 on 2022-02-15 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('django_summernote', '__latest__'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='관련 데이터 번호')),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='django_summernote.attachment')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': '서머노트 첨부파일',
                'verbose_name_plural': '서머노트 첨부파일들',
                'ordering': ['-id'],
            },
        ),
    ]
