# Generated by Django 4.0.2 on 2022-02-07 12:09

from django.db import migrations, models

from products.gen_master_data import gen_master


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_deleted',
        ),
        migrations.AlterField(
            model_name='product',
            name='delete_date',
            field=models.DateTimeField(default=None, blank=True, null=True, verbose_name='삭제날짜'),
        ),
        migrations.RunPython(gen_master)
    ]
